# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interesting',
            field=models.BooleanField(default=False),
        ),
    ]
