# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160909_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
