# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160909_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0435 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interesting',
            field=models.BooleanField(default=False, verbose_name='\u0418\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u044b\u0439'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u041f\u043e\u0441\u0442\u044b'),
        ),
    ]
