# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160909_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='preview_post',
            new_name='preview',
        ),
    ]
