# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(max_length=200, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
