# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160917_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='interesting',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(max_length=300, verbose_name='Превью'),
        ),
    ]
