# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160919_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
        migrations.AddField(
            model_name='post',
            name='source_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_name',
            field=models.CharField(blank=True, default='РИА Новости', max_length=100, null=True, verbose_name='Название источника'),
        ),
    ]
