# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160926_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название источника'),
        ),
    ]
