# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20161003_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='source_name',
        ),
    ]
