# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20161012_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание картинки'),
        ),
    ]
