# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20161012_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview',
        ),
    ]
