# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20161017_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_title',
            field=models.CharField(default='Источник', max_length=15, verbose_name='Название источника'),
        ),
    ]
